### ISSUE TITLE
Publication of the corpus

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/VMCP-upconversion#29]
@LucasHorseshoeBend [commented](https://github.com/Conal-Tuohy/VMCP-upconversion/issues/28#issuecomment-272683399):

> At what stage will we develop a display version?  It will need to be before we get the whole 15K files to _final_? We want  to put up a significant chuck, i.e., the files at final, as soon as we can.

 There are alternatives to XTF that might be worth considering. Gavan and I agreed on using XTF for the proofing phase mainly because it was "to hand" (I was working with it for another client at the time), and because it was known to have quite good faceted browsing features (which I think have proven to be useful for "slicing and dicing" the corpus), but I think its user interface is less than ideal. These may not matter so much for "internal" use by a small group of editors, but for a publication platform they are more significant. We can certainly set up a public version alongside the proofing version (perhaps including just the "final" texts); there's no need to wait until the entire corpus is done I think.

**Comment by LucasHorseshoeBend** [comment]
Please set up an XTF  user-view version with just the Final letters so that we can see it.

However, before we can go fully public, there is a lot of what would be "front matter" in a print version that must be prepared, and I need to get the bibliographies, both Mueller's own works and the editors citations, in a fit state. When Rod gets back from China in February we will need to have a discussion about whether or not we release a beta version accessible from the Mebourne Botanic Garden/Herbarium home page, while we decide on a final release interface. 

At that stage, too, we will need to think about what a downloaded file would look like if a user needs for some reason to have a local copy to work on.

**Comment by Conal-Tuohy** [comment]
Sorry for the delay with this! I've had two demotivations; namely:

1. I've only just started work on a project for Sydney Uni which has been repeatedly delayed, but is now happening, and should be done in about a month. It includes a couple of features which will be a helpful start for the production version of the VMCP:
 - making a more easily customised base version of XTF
 - a number of miscellaneous improvements to the TEI presentation features of XTF
2. I've also asked @gavanjm about hosting. I think it would be preferable for the Gardens to subcontract the hosting and ongoing maintenance to Melbourne Uni, for geographical reasons if no other. I know Gavan is keen in principle to add XTF to their "stable" of services, but I don't have a definite date for that yet

I am going to be away from Thursday until the end of the month, but I am planning to return to work on this project then.

**Comment by LucasHorseshoeBend** [comment]
Given what you had said about consulting Gavan I was not too worried about the apparent lack of progress.  
I was also aware from Gavan that you had a University of Sydney project in hand, which was expected to overlap conceptually and technically with issues in the VMCP.

You raise some important issues about long-term care and maintenance, so I have copied your message to Rod so that he is aware of it when he next sees Gavan, which will probably not be until after he returns from London and Portugal, where he is launching in the week after next the printed edition of the correspondence of an 18th Century savant, which he has been editing with Portuguese colleagues.

**Comment by Conal-Tuohy** [comment]
For the record, I got the go-ahead yesterday from RBGV.

**Comment by LucasHorseshoeBend** [comment]
That is very good news, Conal
Estimated time to a demo version of reader view?
There are some things we will need to do when we know what the layout and presentation is to be, for example introductions to the Apparatus files, and whether we need to create separate files for introductions and so on. 

Best wishes
Arthur

**Comment by LucasHorseshoeBend** [comment]
Now resolved!!
