### ISSUE TITLE
File with an odd title

### ISSUE THREAD

**Issue by LucasHorseshoeBend** [Conal-Tuohy/VMCP-upconversion#33]
See http://vmcp.conaltuohy.com/xtf/view?docId=tei/1880-9/1882/82-09-04a-final.xml 
It shows up with **...** as title.
I opened it, but could not see what might be causing this. It was resaved, so if the effect disappears, well and good, and sorry fro a red herring!

**Comment by Conal-Tuohy** [comment]
Hmmm ... whatever the problem was, it looks like you have indeed fixed it by saving a new version. 

The title is now "82.09.04a ¶ From A. N. Grant ¶ Hillston ¶ 4th September 1882 ¶ Baron ¶ ¶ In obedience to your commands I went yesterday in search of the acacia ¶ and as I anticipated it is now gone out of flower f..."
