### ISSUE TITLE
Authority control on taxonomic names

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/VMCP-upconversion#7]
The plant names could be validated using the [Catalogue of Life](http://www.catalogueoflife.org) or similar.

This would facilitate QA by picking up typos and other problematic names, which could then be edited.

For later publishing, it would facilitate linking from Mueller's citations to relevant online resources.

**Comment by LucasHorseshoeBend** [comment]
Plant names are deliberately listed as in document, with expansion of abbreviated names. Any that are not recognised in one of the major plant name indexes are given a footnote, suggesting an error for the name we think was meant, or saying that it cannt be found; for example see http://vmcp.conaltuohy.com/xtf/view?docId=tei/1870-9/1874/74-08-00e-final.xml at footnotes 2, 3, 4 and 
http://vmcp.conaltuohy.com/xtf/view?docId=tei/1850-9/1856/56-06-18-final.xml at footnote 4, 36, 39 &c.
See  also the introduction to the Index of Botanical names as it appears in the first volume of the Selected correspondence. In dropbox/Rod shared/SELECTED LETTERS/Vol 1/P Index of Botanical Names.doc
That file was resaved as .doc from the version sent to the publishers in 1998.

We have deliberately avoided trying to identify 'current names' in the Mueller correspondence, firstly, because we don't want any names mentioned in the letter transcripts to be treated as published taxons, (we explicitly make that point in the introductory material), although we give a fn saying 'not in APNI'  'not in IPNI '  or 'error for  ....?' where we think that there has been a mistake in the spelling,  as the case may be, to help readers avoid a wild goose chase; secondly, because we are not practising systematic botanists and specimens would need to be compared if we were to be certain of what modern taxon is represented by the name in the MS, especially in pro parte cases; and thirdly, because the example of the Darwin correspondence, where such an attempt has been made using just the literature, shows  that some names current at the time that the annotation was made and  published 30-odd years age are no longer so!

**Comment by LucasHorseshoeBend** [comment]
Do you still need this one open?
From my point of view its a dead issue.
in the future, perhaps if we can get finding, then running a link from the _plant names_ styled material  to Australian Plant Name Index or International Plant name index might be possible, with the non-matches being accountable for in footnotes.
