### ISSUE TITLE
Some direct formatting not preserved

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/VMCP-upconversion#9]
See http://vmcp.conaltuohy.com/xtf/view?docId=tei/1870-9/1872/72-09-26.xml;chunk.id=main;toc.depth=1;toc.id=;brand=default

The line "Dated this 26th day of Septr 1872" should be formatted in a couple of different typefaces.

**Comment by LucasHorseshoeBend** [comment]
I have asked Rod about using colour to identify the text coded as _letter + Times_ or _t-letter + Times_ to indicate the printed part of certificates and the like.
As far as I recall this is the only use of a different typeface coded by direct formatting

But we aso  need to pick up direct formatting of _Letter +underline_ or _letter +double_ underline (possibly also in f_ootnote text_ in  the same way that you have picked up italics
Examples: Underline
http://vmcp.conaltuohy.com/xtf/view?docId=tei/1850-9/1858/58-01-15-final.xml

I cannot quickly fnd an example of a double underline, but I am failrly sure that there are some. I will keep an eye out and add a coment to this issue if I find one

**Comment by LucasHorseshoeBend** [comment]
Rod agrees that if necessary, colour could be used.
Is colour more likely than typeface to be preserved across browsers and users' manipulations of default displays?

**Comment by Conal-Tuohy** [comment]
In the past I would have said so, but I don't think that's significantly the case any more. It used to be that browser's relied exclusively on locally-installed fonts, but now it's possible to use CSS not just to specify fonts by name, but also to actual provide the fonts for download, and there is widespread browser support for this.

**Comment by LucasHorseshoeBend** [comment]
Thanks for the link. The data there show that the machine that I am using will not support the fetaure on Firefox or safari. My Mac was built early 2009, now running  OS 10.6.8  (not the highest it will run, but the highest I can get without having to update a lot of regularly used paid for Apps). I wonder how many potential users are in my position? But my set up will allow us to see what it looks like and whether my choices can make much difference. 

Actually the most important reason for not updating is so that I can run an older version of Word to open archived earlier versions which we sometimes have needed  to use to reinstate corrupted text of the few files that produce  chaotic renderings in their current state:  
http://vmcp.conaltuohy.com/xtf/view?docId=tei/1880-9/1889/89-05-02-corrupted.xml 
Unfortunately the oldest version of that file I have has the same corruption, so it is a matter of re-keying this one.

Just for fun: I remember when one of the research councils in the UK produced a new website, and a very large number of its intended users could not read it. It was designed with colour, and the colours chosen produced tones so similar to each other in B&W, and Universities were so strapped for cash that their replacement cycle for PCs was stretched much longer than the the research council ....

**Comment by Conal-Tuohy** [comment]
It looks to me like web fonts ARE supported on the Safari 4 that comes with OS X 10.6.8. To check it, try visiting [fonts.google.com](http://fonts.google.com/) which is an online repository of web fonts. It should be immediately obvious if it's working. It looks like 93.37% of users would be OK with web fonts.

But it shouldn't be a concern since even where web fonts are not supported, and we can't therefore specify the exact font that's used, we can still fall back to using commonly installed fonts (such as Times and Helvetica), and even to generic "serif" and "sans serif" fonts, and still provide a clear typographical distinction in any browser except a literal museum piece.

**Comment by LucasHorseshoeBend** [comment]
Font.google.com works well in Firefox, but when I tried it in Safari I got

> (≥o≤)

> Your browser is not currently supported. Google Fonts works best on Chrome, Firefox, Edge and Safari.

 

In case for some reason my copy of Safari was corrupted, I deleted it and did a manual reinstall. Same message.
Safari version 5.1.10, OS 10.6.8.

**Comment by Conal-Tuohy** [comment]
I suspect that result from the Google Fonts may be that the interactive features of the site aren't designed to work with Safari 5, rather than that the fonts themselves wouldn't work.

For a laugh I've updated the home page http://vmcp.conaltuohy.com/ to use a "Fraktur" font for the heading. Does it appear for you in Safari?

**Comment by Conal-Tuohy** [comment]
In any case, this discussion of fonts is distinct from my original issue (which still remains). Let's continue it in a new issue, if needed.

**Comment by LucasHorseshoeBend** [comment]
Fraktur appears in both Safari and Firefox browsers.

**Comment by LucasHorseshoeBend** [comment]
This is still important, not just identifying those parts of a file in Times, but also underlines.
Any progress?

**Comment by Conal-Tuohy** [comment]
I haven't come back to this issue, yet, no.

**Comment by Conal-Tuohy** [comment]
This appears to be fixed. The date on the certificate shows two different typefaces.

http://vmcp.conaltuohy.com/xtf/view?docId=tei/Mueller%20letters/1870-9/1872/72-09-26-final.xml;chunk.id=main;toc.depth=1;toc.id=;brand=default

The underlining also appears in the document http://vmcp.conaltuohy.com/xtf/view?docId=tei/Mueller%20letters/1850-9/1858/58-01-15-final.xml;chunk.id=main;toc.depth=1;toc.id=;brand=default

I think this issue should have been closed and was just missed.

**Comment by LucasHorseshoeBend** [comment]
Noted
BUT 
there remain issues with the underlining. 

The test file 00.00.00test in the quarantine folder is the rendering of a file which in Word looks like this:



You will see at 
http://vmcp.conaltuohy.com/xtf/view?docId=tei/Mueller letters/Quarantine folder for problem files/00.00.00test.xml 
that extraneous spaces are introduced in a number of these instances. It is disconcerting to see these, to say the least.


On the other point, we tested the differntiation between fonts with combinations of different operating systems and browsers and only in some was it distinguishable with ease. Hence the decision to colour the text that was printed on the source documents using the style form text. I have been concentrating on files set at final, and have so far coloured up 519 of them, with about 120 left to go. Tedious rather than difficult. 


Best wishes
Arthur
